### PR TITLE
[#99680704] Optimise the running of the script to build the test environment

### LINKED ISSUE #1: Application's role isn't deleted when application is removed
This prevent to bind to an other application with the same name.

### PR DESCRIPTION
**Pull request by keymon**
[#99680704 Optimise the running of the script to build the test environment](https://www.pivotaltracker.com/n/projects/1275640/stories/99680704)
# Context

Given script that allows us to build out a test environment but it is very serial and not resilient to errors. This story is to improve it (doesn't need to be perfect - just better!) to help deploy more quickly and with better resilience against errors.

Main issues were:
- Late feedback: failures happened late in the process.
- Not able to rerun specific parts, or resume execution.
- Sequencial execution (we need parallel execution)
## Scope of the PR

We want to refactor the script to:
- Split the deployment in individual tasks tasks:
  1. Cloning of repos in a cached directory.
  2. Create teams and users
  3. Deploy apps: Create apps, Create DB services, Bind services to apps, Deployment, Scale.
  4. Import database: Do it quicker if possible without dependencies with SSH.
  5. Clean/Remove tasks 
- Allow rerun tasks independently and idempotent. Don't run tasks if unnecessary.
- Use consistent names for users, teams and names.
  - Note, we need to fix [this issue](https://github.com/tsuru/postgres-api/issues/1).
- Allow parallel run
- Keep a independent log of executed deployments for debugging. 
## Implemented solution

In this PR we refactor the script including:
- Use `rake` to separate the tasks and allow parallel runs (`multitask`).
- Refactor the code to allow concurrent runs.
  - Use of thread safe object structures.
  - Log output to independent files.
  - Deploy apps per team in parallel.
- Add logic to check the state and skip tasks that are unnecessary.
- Improve the logging output: less noise and more informative errors.
- Reuse of the [command line helpers from `tsuru-ansible/spec`](https://github.com/alphagov/tsuru-ansible/tree/master/spec) to call `git` and `tsuru` command line tools. This allows better control and capture of output.
  > Note: We are copy&paste code in this case instead of reusing it. This needs to be fixed in the future.
## How to review this PR

> Note: This is a throw away script. The goal is allow us to perform load tests in the platform and extend it in the near future, but throw it away later.

Refer to  `bulk_deploy/README.md` for instructions to run the job. The secret parameters are stored in a secure area ([check card for details](https://www.pivotaltracker.com/n/projects/1275640/stories/99680704)).

We suggest run up to 3 teams, as more might cause too much load in the docker nodes and make the platform unstable.

As a quick reference use this command:

```
bundle install
bundle exec rake \
    admin_pass=mysecretpass \
    environment=test host=tsuru.paas.alphagov.co.uk \
    num_users=10 num_teams=2 \
    dm_api_pg_dump_url="http://somehost.com/full.dump" \
    dm_api_pg_dump_auth_header="Auth: ..." \
    deploy  
```

> **Note:** the script might fail in a given step, usually due issues like:
> - platform stability in the platform due high load. 
> - postgresapi bugs
> - Random application compilation errors (e.g. dependencies down, timeouts)
> 
> If fails, try to rerun the task as described in the README.md
## Serve of postgres dump for DM api in amazon

The postgresql dump for DM api is stored in a amazon, accessible via HTTP using a shared secret. See ([check card for details](https://www.pivotaltracker.com/n/projects/1275640/stories/99680704)) for details.
## Who can review this?

Anybody but @RichardKnop or @keymon.
## Future work

Some ideas for future work:
- Split the deployment in specific tasks: Create apps, Create DB services, Bind services to apps, Deployment, Scale
- Run the Create DB services, Bind services first, as they are the most likely to fail.
- Serve the postgresql dump using temporary app using the `static` platform, instead of serving from amazon.

### CODE REVIEW

**Comment by RichardKnop** [comment]
:+1:

**Comment by dhilton** [comment]
The commit history tells a story of how you came to get to this solution which I think is, in this case important, hence I'm not going to ask for rebasing of the commits.

**Comment by keymon** [comment]
True, this was a long journey going forward and backwards.

I am keen to rewrite the history if it is too messy.

**Comment by actionjack** [comment]
Can you add `tsuru env-set -a postgresapi  WEB_CONCURRENCY=3` to [tsuru-ansible post-tasks](https://github.com/alphagov/tsuru-ansible/blob/master/post-install.yml) so that we don't get any race conditions with the database creation?

**Comment by RichardKnop** [comment]
I don't think it's that easy, you might need to add some packages to requirements.txt to enable concurrency support for gunicorn. Something like:

```
futures==2.1.6
trollius==1.0.1
```

**Comment by dhilton** [comment]
Gunicorn respects the environment variable `WEB_CONCURRENCY` that specifies how many workers it should run. When setting that variable to 3, we observed three gunicorn processes being run according to the logs. 

http://gunicorn-docs.readthedocs.org/en/latest/settings.html#worker-processes

**Comment by dhilton** [comment]
LGTM - Having discussed the outcomes of this PR we're happy that the PR does what the story sets out to deliver, accepting that some of the issues that trip up the testing are relating to the system under test rather than the code delivered here.

**Comment by keymon** [comment]
\o/

**Pull request merged**
