### PR TITLE
[#99680570] Feature/populate elastic search

### PR DESCRIPTION
**Pull request by RichardKnop**
# What

Added the search API app to the list of deployed apps and a task to import Elasticsearch data.

The deployment script works the same way as explained in the README file.

All frontend apps have been reconfigured to point to the correct Elasticsearch endpoint.
# How To Test

On a clean environment in working state (check that Elasticsearch service and broker are running after resuming a previously stopped environment):

```
bundle install
bundle exec rake \
    admin_pass=mysecretpass \
    environment=test host=tsuru.paas.alphagov.co.uk \
    num_users=10 num_teams=2 \
    dm_api_pg_dump_url="http://somehost.com/full.dump" \
    dm_api_pg_dump_auth_header="Auth: ..." \
    deploy  
```
# Who To Review

Somebody other than @RichardKnop

### CODE REVIEW

**Comment by dhilton** [comment]
I keep hitting issues seen in https://github.com/alphagov/tsuru-performance-tests/pull/6 such as:
- Postgresql db instance name clash (instance already exists) postgresapi related issue
- Rake task seems on second run of deploy to fail as key already exists

To actually test the resulting deployment, visit:

http://DM_APP_URL/g-cloud/search?q=platform

**Comment by jimconner** [comment]
It took me two runs to get the bulk deploy to deploy everything correctly - the first attempt resulted in the following error.

```
E, [2015-08-03T12:28:40.744332 #24112] ERROR -- : Failed running team_deployment:bulkt2:java-app:deploy
E, [2015-08-03T12:28:40.744426 #24112] ERROR -- : no implicit conversion of String into Integer
```

After the second attempt, the elasticsearch service broker reported that it was running correctly, and the api application was up and workng OK.

```
+-----------------------------+-------------------------+------------------------------------------------------------------+
| elasticsearchapi            | 1 of 1 units in-service | jimtpt-elasticsearchapi.tsuru2.paas.alphagov.co.uk               |
|                             |                         | elasticsearchapi.jimtpt-hipache.tsuru2.paas.alphagov.co.uk       |
+-----------------------------+-------------------------+------------------------------------------------------------------+


+-----------------------------+-------------------------+------------------------------------------------------------------+
| dm-search-api-bulkt1        | 3 of 3 units in-service | dm-search-api-bulkt1.jimtpt-hipache.tsuru2.paas.alphagov.co.uk   |
+-----------------------------+-------------------------+------------------------------------------------------------------+
| dm-search-api-bulkt2        | 3 of 3 units in-service | dm-search-api-bulkt2.jimtpt-hipache.tsuru2.paas.alphagov.co.uk   |
+-----------------------------+-------------------------+------------------------------------------------------------------+

```

After suspending and resuming the environment, all of the apps and service brokers came to life correctly.

**Comment by keymon** [comment]
As #8 we should rebase this. I will do it.

**Comment by jimconner** [comment]
Now all working successfully with zero errors during deployment. Hitting the merge button.

**Pull request merged**
